[programs.devnet]
tweet = "2rC3dHHk5B91q27fDqCKEZ9qKT8Cgeo1JpQdsdCeNHs5"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/merunas/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
